language: haskell
ghc:
  - "8.4.1"
script: cabal configure --enable-tests --enable-coverage && cabal build && cabal test --show-details=always
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls 4bot-test
  