language: haskell
script: cabal configure --enable-tests --enable-coverage && cabal build && cabal test --show-details=always
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls 4bot-test
